### ISSUE TITLE
Import job doesn't support multiple concurrent executions

### ISSUE THREAD

**Issue by JCL38-ORANGE** [shieldproject/shield-boshrelease#163]
Hello,

With shield 8.0.17, it is now possible to launch in parallel the import job that loads the shield configuration (tenant, retention, storage, system, ...).
Nevertheless on a system with high CPU,  the import job (on server side) doesn't detect that the same configuration items are loaded twice (almost started at the same time). 
Consequently the configuration items are duplicated instead of being updated.
I am going to enclose you some logs and screenshots.
Regards,
Jean-Christophe.

**Comment by jhunt** [comment]
@JCL38-ORANGE,

Did you ever gather those logs / screenshots?
