### ISSUE TITLE
Slack invite link on README.md is not longer valid

### ISSUE THREAD

**Issue by chris-pollard-assurity** [shieldproject/shield-boshrelease#169]
**Problem**
Right at the bottom of the README.md is a `join for free today!` link to a slack invite, however slack reports that  "This invite link is no longer active".

Full link:
`https://join.slack.com/t/shieldproject/shared_invite/enQtMjYyMTAxNjcwMDQ5LTNjZmVhZWMxZmRhNGU4MDBlZWYyNmQ3OWE4OTI5NzA3NzU4MDA2ODAwZDRkMTMxNDk3NjE0MzQ4ZjA3YzBjZmQ%5D`

**Solution**
Please can you update with a new slack invite.

NOTE: the same problem is there with shieldproject.io site on the community page here:
https://shieldproject.io/community/ on the "Join Slack" button.

Thanks in advance
Chris

**Comment by jhunt** [comment]
Updated in both places.  Thanks!
