### ISSUE TITLE
301 response missing Location header

### ISSUE THREAD

**Issue by shitalb358** [shieldproject/shield-boshrelease#170]
Hi Team,
We have shield with v8.0.11, we are trying to take backup of bosh , but test store job failed with below error:
Performing store / retrieve / purge test
           ========================================
           generating an input bit pattern
           Post path/to/s3/bucket:301 response missing Location header
           FAILED: unable to write to storage
           EXITING 2
           shield worker 4 unable to run command against IP:5444
Any idea on this...

**Comment by jhunt** [comment]
Have you tried upgrading to a newer vintage of SHIELD?  8.0.11 was from June of 2018...

**Comment by lordcf** [comment]
It is new fresh deployment of shield with v8.0.11.
This issue is resloved when we created bucket in North Virginia region.
For other regions its gibing same error.

**Comment by shitalb358** [comment]
It is new fresh deployment of shield with v8.0.11.
This issue is resloved when we created bucket in North Virginia region.
For other regions its gibing same error.

**Comment by jhunt** [comment]
A new fresh deployment of SHIELD v8.0.11 is still over a year old.  There have been changes in the codebase, available via more recent releases, that might fix this issue for you, without requiring the us-east-1 region.

**Comment by thomasmitchell** [comment]
https://github.com/shieldproject/shield/pull/569 addressed this. It was released in SHIELD version 8.3.0

**Comment by shitalb358** [comment]
ok, Tanks all  for help and  guidance . Closing this issue for now.
