### ISSUE TITLE
failsafe password issue - overriding has no effects in 8.5.0

### ISSUE THREAD

**Issue by JCL38-ORANGE** [shieldproject/shield-boshrelease#171]
Hello,

The default login/password coming out of the box with admin/shield values.
From my understanding, it is possible to set a strong password (generated by credhub) with the failsafe property. The usage of this property has no effect on my side.
Is it a misunderstanding from my part ? How is it possible to configure that ?
Thanks and regards,
Jean-Christophe.

**Comment by jhunt** [comment]
The failsafe account is only created when there are no other accounts on the system.  This means that once you have booted up SHIELD once, via BOSH, _changing_ the failsafe credentials via the manifest will not have any real effect.  If you log in as the failsafe user, delete the failsafe account, and then reboot the SHIELD core process, you _will_ see the new credentials take effect.

The failsafe user is intended to get you _into_ a SHIELD instance.  If you then change the password of the failsafe account, or provision a new account and delete the failsafe account, we don't want a host reboot or process restart to undo those live changes.
