### ISSUE TITLE
ERROR: failed to set up schema in database

### ISSUE THREAD

**Issue by vOlliestrator** [shieldproject/shield-boshrelease#172]
Hi,

After a failed upgrade to the latest version of Shield following a successful deployment the shieldd service does not start anymore with the following error message:

`
Fri Nov 29 14:12:40 UTC 2019 running any schema migrations
2019-11-29 14:12:40.025589630 +000 UTC /var/vcap/packages/shield/bin/shield-schema: ERROR: failed to set up schema in database at /var/vcap/store/shield/shield.db: table jobs_new already exists
`

It seems that the migration has already started during the first upgrade but failed somewhere during the run. 
Can we remove the shield.db to resolve this issue or is it possible to "force" the migration to step over any issues?

**Comment by jhunt** [comment]
This will be fixed in the 8.6.1 patch release

**Comment by vOlliestrator** [comment]
Thanks James, we will wait for the 8.6.1. patch to be released!
