### ISSUE TITLE
Shield 8.6.1 deploy issue shield.db: table jobs_new already exists

### ISSUE THREAD

**Issue by Klojo** [shieldproject/shield-boshrelease#173]
we see the same errors in shield-bosh-release 8.6.1
##shieldd.log##
2019-12-05 07:58:18.258818792 +000 UTC /var/vcap/packages/shield/bin/shield-schema: ERROR: failed to set up schema in database at /var/vcap/store/shield/shield.db: table jobs_new already exists
Thu Dec  5 07:59:19 UTC 2019 running any schema migrations
The Monit daemon 5.2.5 uptime: 12m
Process 'vault'                     running
Process 'shieldd'                   not monitored
Process 'nginx'                     running
Process 'shield-agent'              Execution failed
System 'system_localhost'           running
##error.log##
2019/12/05 08:15:04 [error] 20335#0: *2318 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xx.xx.xx, server: _, request: "GET /v2/events HTTP/1.1", upstream: "http://127.0.0.1:8080/v2/events", host: "xx.xx.xx.xx" (edited)

**Comment by jhunt** [comment]
Can you run `.schema` inside the SQLite database and post the output here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Klojo** [comment]
Output
sqlite> .schema
sqlite>

**Comment by jhunt** [comment]
This was fixed in release 8.6.2
